const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const Study=require('../study-store'),RecallSync=require('../sync-store');
function payload(id){return JSON.parse(html.match(new RegExp('<script id="'+id+'" type="application/json">([\\s\\S]*?)</script>'))[1]);}
class Element{
  constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.style={};this.events={};this.value='';this.disabled=false;this.hidden=false;this.open=false;this.attributes={};this._text='';this.classes=new Set();this.classList={add:(...x)=>x.forEach(y=>this.classes.add(y)),remove:(...x)=>x.forEach(y=>this.classes.delete(y)),toggle:(x,on)=>{on=on??!this.classes.has(x);on?this.classes.add(x):this.classes.delete(x);return on;},contains:x=>this.classes.has(x)};}
  set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(x=>x.textContent).join('');}
  set innerHTML(v){this.value=v.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&le;/g,'≤').replace(/&amp;/g,'&');}
  set className(v){this.classes=new Set(v.split(/\s+/));}get className(){return [...this.classes].join(' ');}
  append(...x){this.children.push(...x);}prepend(...x){this.children.unshift(...x);}replaceChildren(...x){this.children=x;this._text='';}setAttribute(k,v){this.attributes[k]=v;}
  addEventListener(k,fn){this.events[k]=fn;}click(){if(!this.disabled)return this.onclick?.({target:this,preventDefault(){}});}focus(){}scrollIntoView(){}reset(){}reportValidity(){return true;}checkValidity(){return true;}
  showModal(){this.open=true;}close(){if(!this.open)return;this.open=false;this.events.close?.();}
}
function setup(saved,studyOverride){
  const nodes=new Map();for(const match of html.matchAll(/<([a-z]+)[^>]*\bid="([^"]+)"[^>]*>/g))nodes.set(match[2],new Element(match[1]));
  for(const id of ['deckData','designDeckData','firstSessionData','studyContentData'])nodes.get(id).textContent=JSON.stringify(id==='studyContentData'&&studyOverride?studyOverride:payload(id));
  const views=['today','review','browse','progress','guides'].map(v=>{const e=new Element('button');e.dataset.view=v;return e;});
  const sections=['coding','design','cs','sql'].map(v=>{const e=new Element('button');e.dataset.section=v;return e;});
  const stats=new Element('section'),listeners={},intervals=[];
  const storage=new Map();if(saved)storage.set('recall-interview-prep-v1',JSON.stringify(saved));
  const document={getElementById:id=>nodes.get(id),querySelector:s=>s==='.stats'?stats:null,querySelectorAll:s=>s==='[data-view]'?views:s==='[data-section]'?sections:[],createElement:tag=>new Element(tag),addEventListener:(k,fn)=>listeners[k]=fn,activeElement:new Element('body')};
  let exported;class FakeBlob{constructor(parts){exported=parts.join('');}}
  const sandbox={document,window:{RecallStudy:Study},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},Date,JSON,Math,Set,Number,Object,Array,String,Boolean,Error,Blob:FakeBlob,URL:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}},confirm:()=>true,setTimeout:()=>1,clearTimeout(){},setInterval:fn=>intervals.push(fn),console};
  const historyEntries=[''],location={hash:'',pathname:'/',search:''},windowEvents={};sandbox.window.location=location;sandbox.window.history={pushState(_s,_t,url){location.hash=url.startsWith('#')?url:'';historyEntries.push(location.hash);},replaceState(_s,_t,url){location.hash=url.startsWith('#')?url:'';historyEntries[historyEntries.length-1]=location.hash;},back(){if(historyEntries.length>1)historyEntries.pop();location.hash=historyEntries[historyEntries.length-1];windowEvents.hashchange?.();}};sandbox.window.addEventListener=(k,fn)=>windowEvents[k]=fn;
  const context=vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),context);
  return {nodes,context,storage,listeners,document,tick:()=>intervals.forEach(fn=>fn()),run:code=>vm.runInContext(code,context),state:()=>JSON.parse(vm.runInContext('JSON.stringify(state)',context)),get exported(){return JSON.parse(exported);}};
}
const old={version:1,cards:{'card-7':{due:1999999999999,interval:86400000,reps:2,lapses:1}},log:[{id:'card-7',at:1000000,rating:'good'}]};
function log(s,track='coding'){s.run(`openSession(dailyTasks().find(t=>t.track==='${track}'))`);s.nodes.get('sessionMinutes').value='25';s.nodes.get('sessionNote').value='Test more boundaries';s.nodes.get('sessionForm').onsubmit({preventDefault(){}});}
test('new user starts with three actions, zero sessions, zero card history and no inferred mastery',()=>{const s=setup();assert.equal(s.nodes.get('todayTasks').children.length,3);assert.deepEqual(s.state(),Study.fresh());assert.match(s.nodes.get('todayCount').textContent,/0 of 3/);assert.deepEqual(Array.from(s.run('dailyTasks().map(t=>t.minutes)')),[75,30,15]);});
test('old v1 guest backup is migrated without changing schedule, log or legacy card IDs',()=>{const s=setup(old);assert.deepEqual(s.state().cards,old.cards);assert.deepEqual(s.state().log,old.log);assert.deepEqual(s.state().sessions,[]);assert.equal(s.run('codingDeck.length'),121);assert.equal(s.run("codingDeck[7].id"),'card-7');});
test('session submission is idempotent, persists refresh, and undo does not touch cards',()=>{const s=setup(old);log(s);s.nodes.get('sessionForm').onsubmit({preventDefault(){}});assert.equal(s.state().sessions.length,1);const restored=setup(s.state());assert.equal(restored.state().sessions[0].minutes,25);assert.match(restored.nodes.get('todayCount').textContent,/1 of 3/);restored.run('undoSession(state.sessions[0].id)');assert.equal(restored.state().sessions.length,0);assert.deepEqual(restored.state().cards,old.cards);});
test('opening, canceling or closing a practice prompt never logs progress',()=>{const s=setup();s.run('openExercise(dailyTasks()[0])');assert.equal(s.nodes.get('exerciseDialog').open,true);assert.equal(s.run("document.getElementById('exerciseContent').children.filter(x=>x.className==='exercise-step')[1].hidden"),true);s.nodes.get('closeExercise').click();s.run('openSession(dailyTasks()[0])');s.nodes.get('closeSession').click();s.nodes.get('sessionForm').onsubmit({preventDefault(){}});assert.equal(s.state().sessions.length,0);});
test('design filtering, source links, due review, double rating and cross-section undo work',()=>{const s=setup();s.run("setSection('design');reveal()");assert.equal(s.run('filtered().length'),36);assert.equal(s.run("filtered().every(c=>c.id.startsWith('sd-'))"),true);assert.equal(s.run('answerNode(current).children[1].href.startsWith("https://")'),true);s.run("rate('good');rate('good')");assert.equal(s.state().log.length,1);s.run("setSection('coding');undo()");assert.equal(s.state().log.length,0);assert.equal(s.run('section'),'design');assert.equal(s.run('revealed'),true);});
test('free practice does not alter schedules or create practice sessions',()=>{const s=setup(old);s.run("setSection('design');setMode('practice');reveal();rate('easy')");assert.deepEqual(s.state().cards,old.cards);assert.deepEqual(s.state().log,old.log);assert.equal(s.state().sessions.length,0);});
test('new backup export/restore roundtrip keeps all sessions and both decks',async()=>{const s=setup(old);log(s,'design');s.run("setSection('design');reveal();rate('hard')");s.nodes.get('export').click();const backup=s.exported;assert.equal(backup.sessions.length,1);const fresh=setup();const file={size:1000,text:async()=>JSON.stringify(backup)},target={files:[file],value:'test'};await fresh.nodes.get('importFile').onchange({target});assert.deepEqual(fresh.state().cards,s.state().cards);assert.deepEqual(fresh.state().sessions,s.state().sessions);assert.equal(target.value,'');});
test('cancel restore and invalid restore leave progress intact, same file can be selected again',async()=>{const s=setup(old);s.context.confirm=()=>false;const target={files:[{size:1000,text:async()=>JSON.stringify(Study.fresh())}],value:'test'};await s.nodes.get('importFile').onchange({target});assert.deepEqual(s.state().cards,old.cards);assert.equal(target.value,'');s.context.confirm=()=>true;target.files[0].text=async()=>JSON.stringify({...old,sessions:[{bad:true}]});target.value='test';await s.nodes.get('importFile').onchange({target});assert.deepEqual(s.state().cards,old.cards);assert.equal(target.value,'');});
test('account transition clears session modal and prevents stale guest submission',()=>{const s=setup(old);s.run('openSession(dailyTasks()[0])');s.run('window.recallApp.replace(window.recallApp.empty())');s.nodes.get('sessionForm').onsubmit({preventDefault(){}});assert.equal(s.nodes.get('sessionDialog').open,false);assert.equal(s.state().sessions.length,0);});
test('loading or conflicted cloud state blocks session and rating mutation',()=>{const s=setup();s.context.window.recallCloud={canEdit:()=>false};log(s);s.run("setSection('design');reveal();rate('good')");assert.deepEqual(s.state(),Study.fresh());});
test('valid rejects malformed and duplicate sessions while accepting old backups',()=>{const s=setup(old);assert.equal(s.run('valid(state)'),true);log(s);const valid=s.context.window.recallApp.valid;assert.equal(valid(s.state()),true);const duplicate=s.state();duplicate.sessions.push({...duplicate.sessions[0],id:'another'});assert.equal(valid(duplicate),false);const invalid=s.state();invalid.sessions[0].minutes=0;assert.equal(valid(invalid),false);});
test('missed days create no backlog and tomorrow advances only the completed track',()=>{const date=new Date(2026,9,5,12).getTime(),state=Study.fresh();const entry={id:'test',taskKey:'2026-10-05:coding',date:'2026-10-05',track:'coding',at:date,minutes:20,topic:'Attempt',assistance:'none',note:'',outcome:'completed'};const next=Study.record(state,entry),tasks=Study.today(next,new Date(2026,9,9,12).getTime());assert.equal(tasks.length,3);assert.equal(tasks[0].title,'Practice one useful pattern');assert.equal(tasks[1].title,'Build a first design');assert.equal(tasks.filter(t=>t.completed).length,0);});
test('all new card IDs unique, all source URLs HTTPS, payload matches source files',()=>{const cards=payload('designDeckData');assert.deepEqual(cards,JSON.parse(fs.readFileSync(path.join(root,'system-design.json'))));assert.equal(new Set(cards.map(c=>c.id)).size,36);assert(cards.every(c=>c.source.url.startsWith('https://')&&c.back.split(/\s+/).length<=90));assert.deepEqual(payload('firstSessionData'),JSON.parse(fs.readFileSync(path.join(root,'first-session.json'))));});
test('existing account sync persists and loads new practice sessions without schema change',async()=>{const app=setup();log(app,'behavioral');let row=null;const remote={load:async()=>row,save:async(id,progress,revision)=>{row={progress,revision:revision+1};return revision+1;}};const store={getItem:()=>null,setItem(){}};const sync=new RecallSync({remote,storage:store,valid:app.context.window.recallApp.valid,onState(){},onStatus(){}});await sync.open('test-user');sync.change(app.state());await sync.flush();let restored;const other=new RecallSync({remote,storage:store,valid:app.context.window.recallApp.valid,onState:s=>restored=s,onStatus(){}});await other.open('test-user');assert.equal(restored.sessions.length,1);assert.equal(restored.sessions[0].track,'behavioral');});

test('Today timer preserves task DOM during same-day navigation and modal use',()=>{const s=setup(),original=s.nodes.get('todayTasks').children[0];s.tick();assert.equal(s.nodes.get('todayTasks').children[0],original);s.run("openSession(dailyTasks()[0]);lastTodayDate='old-date'");s.tick();assert.equal(s.nodes.get('todayTasks').children[0],original);s.nodes.get('closeSession').click();s.tick();assert.notEqual(s.nodes.get('todayTasks').children[0],original);});
test('a queued close event cannot clear a newly opened session',()=>{const s=setup(),dialog=s.nodes.get('sessionDialog');let delayed;dialog.close=()=>{dialog.open=false;delayed=dialog.events.close;};s.run('openSession(dailyTasks()[0])');s.nodes.get('closeSession').click();s.run('openSession(dailyTasks()[1])');delayed();assert.equal(s.run('activeTask.track'),'design');assert.equal(dialog.open,true);});

test('updating a partial session to completed keeps one log and total minutes',()=>{const s=setup(old);log(s);const first=s.state().sessions[0];s.run('openSession(dailyTasks()[0])');assert.equal(s.nodes.get('sessionMinutes').value,25);s.nodes.get('sessionMinutes').value='45';s.nodes.get('sessionOutcome').value='completed';s.nodes.get('sessionForm').onsubmit({preventDefault(){}});assert.equal(s.state().sessions.length,1);assert.equal(s.state().sessions[0].id,first.id);assert.equal(s.state().sessions[0].at,first.at);assert.equal(s.state().sessions[0].minutes,45);assert.equal(s.state().sessions[0].outcome,'completed');assert.deepEqual(s.state().cards,old.cards);});
test('partial and legacy-outcome history keep the starter prompt with a Continue or Review label',()=>{const date=Study.dayKey(Date.now()-86400000*2);const entry={id:'earlier',taskKey:date+':coding',date,track:'coding',at:Date.now()-86400000*2,minutes:20,topic:'An attempt',assistance:'none',note:'',outcome:'partial'};const s=setup({...old,sessions:[entry]});assert.equal(s.run('dailyTasks()[0].title'),'Continue: Try two C# problems');assert.equal(s.run('Boolean(dailyTasks()[0].exercise)'),true);assert.equal(s.run('dailyTasks()[0].planIndex'),0);const legacy={...entry};delete legacy.outcome;const other=setup({...old,sessions:[legacy]});assert.equal(other.run('dailyTasks()[0].title'),'Review: Try two C# problems');assert.deepEqual(other.state().sessions,[legacy]);});

const guideFixture={cards:[{id:'cs-test-runtime',section:'cs',tags:'cs-runtime',front:'Runtime?',back:'A runtime answer',guideId:'runtime',guideAnchor:'memory'},{id:'sql-test-select',section:'sql',tags:'sql-basics',front:'Select?',back:'SELECT name FROM people;',guideId:'select',guideAnchor:'query'}],guides:[{id:'runtime',section:'cs',title:'Runtime basics',summary:'Memory and execution',sections:[{id:'memory',title:'Memory model',paragraphs:['A detailed explanation.'],code:'public class Example {}',language:'csharp'}],sources:[{title:'Runtime docs',url:'https://learn.microsoft.com/dotnet/'}]},{id:'select',section:'sql',title:'First SQL query',summary:'Start with rows and columns',sections:[{id:'query',title:'Read rows',paragraphs:['A small worked example.'],code:'SELECT name FROM people;',language:'sql'}],sources:[{title:'PostgreSQL docs',url:'https://www.postgresql.org/docs/current/tutorial-select.html'}]}],cardGuides:{'card-0':{guideId:'runtime',anchor:'memory'}},groups:{},coverage:[]};
test('guide links open relevant code without rating; browser Back restores exact card and reveal state',()=>{const s=setup(old,guideFixture);s.run("setSection('coding');reveal()");const id=s.run('current.id'),before=s.state();s.run("openGuide('runtime','memory')");assert.equal(s.run('view'),'guides');assert.equal(s.run('selectedGuide.id'),'runtime');assert.equal(s.run('selectedGuideAnchor'),'memory');assert.match(s.nodes.get('guideDetail').textContent,/public class Example/);assert.deepEqual(s.state(),before);s.context.window.history.back();assert.equal(s.run('view'),'review');assert.equal(s.run('section'),'coding');assert.equal(s.run('current.id'),id);assert.equal(s.run('revealed'),true);assert.deepEqual(s.state(),before);});
test('new section ratings, cross-section undo and backup validity preserve old progress',()=>{const s=setup(old,guideFixture);s.run("setSection('sql');reveal();rate('good')");assert.equal(s.state().cards['sql-test-select'].reps,1);assert.deepEqual(s.state().cards['card-7'],old.cards['card-7']);s.run("setSection('cs');undo()");assert.equal(s.run('section'),'sql');assert.equal(s.state().cards['sql-test-select'],undefined);assert.deepEqual(s.state().cards,old.cards);assert.equal(s.context.window.recallApp.valid({...old,cards:{...old.cards,'cs-test-runtime':old.cards['card-7']}}),true);});
test('guide library filters/searches without changing state and guide section switching keeps free-practice queue',()=>{const s=setup(old,guideFixture);s.run("setSection('coding');setMode('practice');reveal()");const queued=s.run('practiceQueue.length'),id=s.run('current.id');s.run("openGuide('runtime','memory');setSection('sql')");assert.equal(s.run('view'),'guides');assert.equal(s.nodes.get('guideList').children.length,1);s.nodes.get('guideSearch').value='unfindable phrase';s.nodes.get('guideSearch').oninput();assert.match(s.nodes.get('guideList').textContent,/No guides match/);s.run('returnFromGuide()');assert.equal(s.run('current.id'),id);assert.equal(s.run('practiceQueue.length'),queued);assert.equal(s.run('mode'),'practice');assert.deepEqual(s.state().cards,old.cards);});
test('broken/encoded guide addresses recover safely; malicious guide text is not HTML',()=>{const s=setup(old,guideFixture);s.run("navigateHash('#guide/unknown')");assert.equal(s.run('selectedGuide'),null);assert.match(s.nodes.get('guideResultsLabel').textContent,/could not be found/);s.run("navigateHash('#guide/%ZZ')");assert.match(s.nodes.get('guideResultsLabel').textContent,/invalid/);s.run("navigateHash('#guide/runtime/no-such-anchor')");assert.equal(s.run('selectedGuide.id'),'runtime');assert.equal(s.run('selectedGuideAnchor'),'');assert.match(s.nodes.get('guideDetail').textContent,/section was not found/);assert.deepEqual(s.state().cards,old.cards);});
test('account replacement while reading a guide never changes legacy state or logs a practice',()=>{const s=setup(old,guideFixture);s.run("setSection('cs');reveal();openGuide('runtime','memory');window.recallApp.replace(window.recallApp.empty());returnFromGuide()");assert.deepEqual(s.state(),Study.fresh());assert.equal(s.nodes.get('sessionDialog').open,false);});
test('study shortcuts are ignored while reading a guide or typing into a guide search',()=>{const s=setup(old,guideFixture);s.run("setSection('cs');reveal();openGuide('runtime','memory')");for(const key of ['1','2','3','4',' '])s.listeners.keydown({key,code:key===' '?'Space':'Digit'+key,preventDefault(){throw Error('Guide shortcut intercepted');}});assert.deepEqual(s.state().cards,old.cards);s.run('openGuideLibrary()');s.document.activeElement=new Element('input');s.listeners.keydown({key:'1',code:'Digit1',preventDefault(){throw Error('Search shortcut intercepted');}});assert.deepEqual(s.state().cards,old.cards);});
test('new section IDs roundtrip through existing cloud adapter and backup with old reviews intact',async()=>{const s=setup(old,guideFixture);s.run("setSection('cs');reveal();rate('hard');setSection('sql');reveal();rate('good')");log(s);s.nodes.get('export').click();const backup=s.exported;const restored=setup(null,guideFixture);await restored.nodes.get('importFile').onchange({target:{files:[{size:1000,text:async()=>JSON.stringify(backup)}],value:'backup'}});assert.deepEqual(restored.state().cards,s.state().cards);assert.deepEqual(restored.state().log,s.state().log);assert.deepEqual(restored.state().sessions,s.state().sessions);let row=null,loaded;const remote={load:async()=>row,save:async(_id,progress,revision)=>{row={progress,revision:revision+1};return revision+1;}},storage={getItem:()=>null,setItem(){}};const a=new RecallSync({remote,storage,valid:s.context.window.recallApp.valid,onState(){},onStatus(){}});await a.open('account');a.change(s.state());await a.flush();const b=new RecallSync({remote,storage,valid:s.context.window.recallApp.valid,onState:x=>loaded=x,onStatus(){}});await b.open('account');assert.deepEqual(JSON.parse(JSON.stringify(loaded)),s.state());});
test('leaving a guide for Study renders a card from the selected section',()=>{const s=setup(old,guideFixture);s.run("setSection('coding');reveal();openGuide('runtime','memory');setSection('sql');leaveGuideRoute();view='review';render()");assert.equal(s.run('current.section'),'sql');assert.equal(s.run('revealed'),false);});
test('section library links are reloadable and invalid section links recover',()=>{const s=setup(old,guideFixture);s.run("navigateHash('#guides/sql')");assert.equal(s.run('section'),'sql');assert.equal(s.run('view'),'guides');assert.match(s.nodes.get('guideList').textContent,/First SQL query/);s.run("navigateHash('#guides/not-a-section')");assert.match(s.nodes.get('guideResultsLabel').textContent,/section was not found/);assert.deepEqual(s.state().cards,old.cards);});
