const test=require('node:test'),assert=require('node:assert/strict');
const Study=require('../study-store');
const at=day=>new Date(2026,9,day,12).getTime();
function entry(day,{track='coding',outcome='completed',minutes=30,id}={}){const date=Study.dayKey(at(day));return {id:id||`${track}-${day}`,taskKey:`${date}:${track}`,date,track,at:at(day),minutes,topic:'Generic practice',assistance:'none',note:'',...(outcome?{outcome}:{})};}
function withEntries(entries){return {...Study.fresh(),sessions:entries};}
test('a partial attempt resumes the same task and does not count as a completed step',()=>{const tasks=Study.today(withEntries([entry(5,{outcome:'partial'})]),at(6));assert.equal(tasks[0].planIndex,0);assert.equal(tasks[0].completedCount,0);assert.equal(tasks[0].continuation,'partial');});
test('a legacy log without an outcome requests review without inferring completion',()=>{const tasks=Study.today(withEntries([entry(5,{outcome:null})]),at(6));assert.equal(tasks[0].planIndex,0);assert.equal(tasks[0].continuation,'review');assert.equal(tasks[0].completedCount,0);});
test('successive partial attempts cannot move an already-started track forward',()=>{const tasks=Study.today(withEntries([entry(1),entry(2),entry(3,{outcome:'partial'}),entry(4,{outcome:'partial'})]),at(5));assert.equal(tasks[0].planIndex,2);assert.equal(tasks[0].completedCount,2);assert.equal(tasks[0].continuation,'partial');});
test('only completed practice advances, independently for each track',()=>{const tasks=Study.today(withEntries([entry(5),entry(5,{track:'design',outcome:'partial'}),entry(5,{track:'behavioral',outcome:null})]),at(6));assert.deepEqual(tasks.map(x=>x.planIndex),[1,0,0]);assert.deepEqual(tasks.map(x=>x.continuation),[null,'partial','review']);});
test('five or more completed sessions never cycle back to an initial baseline',()=>{for(const track of Study.tracks){for(let count=1;count<=25;count++){const entries=Array.from({length:count},(_,i)=>entry(i+1,{track}));const task=Study.today(withEntries(entries),at(count+2)).find(x=>x.track===track);assert(task.planIndex>=1&&task.planIndex<=4);assert.notEqual(task.title,'Establish a coding baseline');assert.notEqual(task.title,'Build a first design');assert.equal(task.completedCount,count);}}});
test('repeat saves and same-day edits keep one record per track and no extra credit',()=>{const first=entry(5,{outcome:'partial'});let state=Study.record(Study.fresh(),first);state=Study.record(state,first);state=Study.record(state,{...first,id:'unrelated-second-id',outcome:'completed'});assert.equal(state.sessions.length,1);assert.equal(state.sessions[0].outcome,'partial');state=Study.record(state,{...first,minutes:45,outcome:'completed'});state=Study.record(state,entry(5,{track:'design'}));state=Study.record(state,entry(5,{track:'behavioral'}));assert.equal(state.sessions.length,3);assert.equal(state.sessions[0].minutes,45);assert.deepEqual(Study.today(state,at(6)).map(x=>x.completedCount),[1,1,1]);});
test('completion advances only after local midnight, with no automatic completion of the next day',()=>{const state=withEntries([entry(5)]),before=new Date(2026,9,5,23,59,59).getTime(),after=new Date(2026,9,6,0,0,0).getTime();const current=Study.today(state,before)[0],next=Study.today(state,after)[0];assert.equal(current.planIndex,0);assert.equal(current.completed.outcome,'completed');assert.equal(next.planIndex,1);assert.equal(next.completed,null);assert.equal(next.taskKey,'2026-10-06:coding');});
test('partial state survives midnight and missed days without generating a backlog',()=>{const state=withEntries([entry(5,{outcome:'partial'})]),tasks=Study.today(state,at(20));assert.equal(tasks.length,3);assert.equal(tasks[0].continuation,'partial');assert.equal(tasks[0].planIndex,0);assert.equal(tasks[0].completed,null);});
test('planner reads and session edits retain legacy reviews and earlier session history',()=>{const card={due:1999999999999,interval:86400000,reps:4,lapses:1},old={version:1,cards:{'card-120':card},log:[{id:'card-120',at:at(1),rating:'good'}],sessions:[entry(1),entry(2,{outcome:'partial'})]};const snapshot=JSON.stringify(old);Study.today(old,at(5));assert.equal(JSON.stringify(old),snapshot);const updated=Study.record(old,{...old.sessions[1],outcome:'completed'});assert.deepEqual(updated.cards,old.cards);assert.deepEqual(updated.log,old.log);assert.deepEqual(updated.sessions[0],old.sessions[0]);assert.equal(updated.sessions.length,2);});
