const test=require('node:test'),assert=require('node:assert/strict');
const RecallSync=require('../sync-store');
const progress=n=>({version:1,cards:{},log:Array.from({length:n},(_,i)=>({at:i}))});
const valid=p=>p?.version===1&&p.cards&&Array.isArray(p.log);
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function setup(remote){const values=new Map();let displayed,status;const sync=new RecallSync({remote,valid,storage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},onState:s=>displayed=s,onStatus:s=>status=s});return {sync,values,get displayed(){return displayed;},get status(){return status;}};}
test('loads account progress, saves confirmed revision, and isolates cache keys',async()=>{let saved;const s=setup({load:async()=>({progress:progress(2),revision:3}),save:async(id,p,r)=>{saved={id,p,r};return r+1;}});await s.sync.open('alice');assert.equal(s.displayed.log.length,2);s.sync.change(progress(4));await s.sync.flush();assert.equal(saved.id,'alice');assert.equal(saved.r,3);assert.equal(s.status,'saved');assert.equal(JSON.parse(s.values.get('recall-account-v1:alice')).revision,4);assert(!s.values.has('recall-account-v1:bob'));});
test('new accounts start empty and first write uses revision zero',async()=>{const s=setup({load:async()=>null,save:async(id,p,r)=>{assert.equal(r,0);return 1;}});await s.sync.open('new');assert.equal(s.displayed.log.length,0);s.sync.change(progress(1));await s.sync.flush();assert.equal(s.status,'saved');});
test('edits during a save trigger a subsequent save without losing the latest edits',async()=>{let resolve;const writes=[];const s=setup({load:async()=>null,save:async(id,p,r)=>{writes.push({p,r});if(writes.length===1)await new Promise(res=>resolve=res);return r+1;}});await s.sync.open('alice');s.sync.change(progress(1));const pending=s.sync.flush();await tick();s.sync.change(progress(2));resolve();await pending;assert.deepEqual(writes.map(w=>w.p.log.length),[1,2]);assert.deepEqual(writes.map(w=>w.r),[0,1]);assert.equal(s.sync.context.dirty,false);});
test('a stale account load cannot show one user’s progress to another',async()=>{let resolve;const s=setup({load:id=>id==='alice'?new Promise(r=>resolve=r):Promise.resolve({progress:progress(5),revision:1}),save:async()=>2});const a=s.sync.open('alice');await s.sync.open('bob');resolve({progress:progress(9),revision:1});await a;assert.equal(s.displayed.log.length,5);assert.equal(s.sync.context.id,'bob');});
test('a save finishing after logout does not change guest status',async()=>{let resolve;const s=setup({load:async()=>null,save:()=>new Promise(r=>resolve=r)});await s.sync.open('alice');s.sync.change(progress(1));const save=s.sync.flush();await tick();s.sync.close();resolve(1);await save;assert.equal(s.status,'guest');assert.equal(s.sync.context,null);assert.equal(JSON.parse(s.values.get('recall-account-v1:alice')).dirty,false);});
test('failed save keeps dirty recovery copy and retry recovers',async()=>{let failed=true;const s=setup({load:async()=>null,save:async()=>{if(failed)throw Error('offline');return 1;}});await s.sync.open('alice');s.sync.change(progress(2));assert.equal(await s.sync.flush(),false);assert.equal(s.status,'error');assert.equal(JSON.parse(s.values.get('recall-account-v1:alice')).dirty,true);failed=false;await s.sync.retry();assert.equal(s.status,'saved');});
test('load failure without a cache blocks writes instead of overwriting unseen progress',async()=>{const s=setup({load:async()=>{throw Error('offline');},save:async()=>1});await s.sync.open('alice');assert.equal(s.sync.canEdit(),false);assert.throws(()=>s.sync.change(progress(1)));});
test('offline load restores only this user’s existing recovery copy',async()=>{const s=setup({load:async()=>{throw Error('offline');},save:async()=>1});s.values.set('recall-account-v1:alice',JSON.stringify({progress:progress(7),revision:2,dirty:true}));await s.sync.open('alice');assert.equal(s.displayed.log.length,7);assert(s.sync.canEdit());await s.sync.open('bob');assert.equal(s.sync.canEdit(),false);});
test('divergent offline cache stops sync and keeps exportable local progress',async()=>{let saves=0;const s=setup({load:async()=>({progress:progress(5),revision:3}),save:async()=>{saves++;return 4;}});s.values.set('recall-account-v1:alice',JSON.stringify({progress:progress(7),revision:2,dirty:true}));await s.sync.open('alice');assert.equal(s.status,'conflict');assert.equal(s.displayed.log.length,7);assert.equal(s.sync.canEdit(),false);await s.sync.flush();assert.equal(saves,0);await s.sync.useCloud();assert.equal(s.displayed.log.length,5);assert.equal(s.status,'saved');});
test('remote compare-and-swap conflict never silently overwrites newer progress',async()=>{const s=setup({load:async()=>({progress:progress(2),revision:2}),save:async()=>{throw Object.assign(Error('conflict'),{conflict:true});}});await s.sync.open('alice');s.sync.change(progress(3));await s.sync.flush();assert.equal(s.status,'conflict');assert.equal(s.sync.context.progress.log.length,3);assert.equal(s.sync.context.revision,2);});
